### ISSUE TITLE
Não consigo excluir!

### ISSUE THREAD

**Issue by gustavo96ma** [Joaopedroo201/lista-afazeres-flutter-unicv#1]
Não consigo excluir uma tarefa, acho que vocês esqueceram de implementar essa parte :/

**Comment by Joaopedroo201** [comment]
Aah professor, eu troquei

**Comment by Joaopedroo201** [comment]
Eu troquei o excluir pra manter o checkbox com estado de checked, pensei que não iria ter problemas e que ficaria mais dahora

**Comment by gustavo96ma** [comment]
Mas fazia parte dos requisitos a função de excluir uma tarefa 😱

**Comment by Joaopedroo201** [comment]
perdoe-me faltou atenção na hora de ler, posso fazer aqui na parte da noite e subir a versão com exclusão?

**Comment by gustavo96ma** [comment]
Pode 🥺

Em qua., 24 de abr. de 2024 17:20, João Pedro ***@***.***>
escreveu:

**Comment by Joaopedroo201** [comment]
Thanks professor, só vou chegar na facul qnd pegar o pc já modifico e te aviso no email

**Comment by Joaopedroo201** [comment]
Te enviei no email @gustavo96ma

**Comment by gustavo96ma** [comment]
Corrigido!
